Repository flexcompute/Flow360, pull requests merged in 2024-03, with the labels that each got.

#190 Fix crash when running _distribute_shared_output_fields with output_fields being None
  flow360/component/flow360_params/flow360_output.py
Labels: current-version, hotfix

#195 Fix the reconstructionGradientLimiter updater
  flow360/component/flow360_params/solvers.py
  tests/data/cases/case_7.json
  tests/test_updater.py
Labels: current-version, hotfix

#194 Found a issue that the unit conversion is skipped for some reason
  flow360/component/flow360_params/flow360_output.py
  flow360/component/flow360_params/solvers.py
  tests/params/test_outputs.py
  tests/test_validator_valid_output_fields.py
Labels: bug, help wanted, current-version

#200 Fix model_type missing in the turb solver updater
  flow360/component/flow360_params/solvers.py
  tests/data/cases/case_5.json
  tests/data/cases/case_udd.json
Labels: current-version

#154 remove CfTagent and CfNormal as they are no longer supported
  flow360/component/flow360_params/flow360_fields.py
  flow360/examples/actuatorDisk/flow360.json
  flow360/examples/betDisk/flow360.json
  flow360/examples/betLine/flow360.json
  flow360/examples/betLine/release-21.3.3.0ge/flow360.json
Labels: next-version

#170 Apply porous media changes
  flow360/__init__.py
  flow360/component/constants.py
  flow360/component/flow360_params/conversions.py
  flow360/component/flow360_params/exposed_units.py
  flow360/component/flow360_params/flow360_params.py
  flow360/component/flow360_params/unit_system.py
  flow360/component/flow360_params/volume_zones.py
  tests/params/test_porous_media.py
  tests/test_flow360_params.py
  tests/test_schema_generator.py
  tests/test_unit_system.py
Labels: future-release
