Repository flexcompute/Flow360, pull requests merged in 2025-03, with the labels that each got.

#771 [RC-25.2] [FL-220] fix(): Added flag to indicate a boundary may be deleted.
  flow360/component/simulation/framework/base_model.py
  flow360/component/simulation/meshing_param/face_params.py
  flow360/component/simulation/meshing_param/params.py
  flow360/component/simulation/meshing_param/volume_params.py
  flow360/component/simulation/models/surface_models.py
  flow360/component/simulation/outputs/outputs.py
  flow360/component/simulation/primitives.py
  flow360/component/simulation/services.py
  flow360/component/simulation/simulation_params.py
  flow360/component/simulation/user_defined_dynamics/user_defined_dynamics.py
  flow360/component/simulation/validation/validation_context.py
  flow360/component/simulation/validation/validation_simulation_params.py
  flow360/component/simulation/validation_utils.py
  flow360/component/simulation/web/asset_base.py
  tests/ref/simulation/service_init_geometry.json
  tests/ref/simulation/service_init_volume_mesh.json
  tests/simulation/framework/test_context_validators.py
  tests/simulation/params/data/geometry_metadata_asset_cache.json
  tests/simulation/params/test_validators_params.py
Labels: Hotfix-pending

#820 [RC-25.2 HOTFIX] [SCFD-4593] added wall rotation specification for wall BC (#811)
  flow360/component/simulation/models/surface_models.py
  flow360/component/simulation/translator/solver_translator.py
  tests/simulation/params/test_rotation.py
  tests/simulation/translator/ref/Flow360_boundaries.json
  tests/simulation/translator/test_solver_translator.py
Labels: hotfix

#826 [Hotfix RC-25.2]Add use_beta_mesher to params before submission
  flow360/component/project.py
  flow360/component/project_utils.py
Labels: N-phase1

#827 Add use_beta_mesher to params before submission
  flow360/component/project.py
  flow360/component/project_utils.py
Labels: N-phase1

#817 [SCFD-4591] Add face/edge renaming function
  flow360/component/geometry.py
  tests/simulation/asset/test_geometry.py
Labels: N-phase1

#748 [Hotfix][FL-226] TimeAverageProbeOutput supports frequency=-1 (#738)
  flow360/component/simulation/outputs/outputs.py
Labels: BLOCKED

#789 User expression support [POC]
  flow360/component/simulation/blueprint/__init__.py
  flow360/component/simulation/blueprint/codegen/__init__.py
  flow360/component/simulation/blueprint/codegen/generator.py
  flow360/component/simulation/blueprint/codegen/parser.py
  flow360/component/simulation/blueprint/core/__init__.py
  flow360/component/simulation/blueprint/core/context.py
  flow360/component/simulation/blueprint/core/expressions.py
  flow360/component/simulation/blueprint/core/function.py
  flow360/component/simulation/blueprint/core/statements.py
  flow360/component/simulation/blueprint/utils/__init__.py
  flow360/component/simulation/blueprint/utils/operators.py
  flow360/component/simulation/blueprint/utils/whitelisted.py
  flow360/component/simulation/expressions.py
  tests/simulation/test_expressions.py
Labels: expressions

#824 [SCFD-4744] added access to mesh bounding box data
  flow360/component/results/base_results.py
  flow360/component/results/case_results.py
  flow360/component/volume_mesh.py
  flow360/plugins/report/utils.py
  tests/data/vm-11111111-1111-1111-1111-111111111111/meshBoundaryBoundingBox.json
  tests/data/vm-11111111-1111-1111-1111-111111111111/meshStats.json
  tests/data/vm-11111111-1111-1111-1111-111111111111/simulation.json
  tests/data/vm-1cfdec99-3ce3-428c-85f8-2054812b2ddc/meshBoundaryBoundingBox.json
  tests/report/test_report_items.py
  tests/test_results.py
  tests/utils.py
  tests/volume_mesh/test_volume_mesh.py
Labels: N-phase1

#846 [Release 25.4] added streamtrace interface for points, lines, and trapezoid
  flow360/__init__.py
  flow360/component/project_utils.py
  flow360/component/simulation/entity_info.py
  flow360/component/simulation/outputs/output_entities.py
  flow360/component/simulation/outputs/outputs.py
  flow360/component/simulation/translator/solver_translator.py
  flow360/component/simulation/validation/validation_output.py
  tests/simulation/translator/test_output_translation.py
Labels: N-phase1
