Repository flexcompute/Flow360, pull requests merged in 2025-02, with the labels that each got.

#706 feat(): Added function to compute Reynolds number
  flow360/component/simulation/operating_condition/operating_condition.py
  tests/simulation/params/test_simulation_params.py
Labels: Hotfix-pending

#683 change location and keys of X/Y_slicing_forceDistribution.csv
  flow360/component/results/case_results.py
  tests/data/00000000-0000-0000-0000-000000000000/results/X_slicing_forceDistribution.csv
  tests/data/00000000-0000-0000-0000-000000000000/results/Y_slicing_forceDistribution.csv
  tests/data/00000000-0000-0000-0000-000000000000/results/postprocess/X_slicing_forceDistribution.csv
  tests/data/00000000-0000-0000-0000-000000000000/results/postprocess/Y_slicing_forceDistribution.csv
  tests/test_results.py
Labels: future-release

#676 Extend report generation feature for service tests
  flow360/component/results/case_results.py
  flow360/plugins/report/report_items.py
  flow360/plugins/report/utils.py
  tests/test_results.py
Labels: next release

#713 [SCFD-4264] fix(): Add validation to prevent steady simulation with aeroacoustics
  flow360/component/simulation/simulation_params.py
  flow360/component/simulation/validation/validation_output.py
  tests/simulation/params/test_validators_output.py
  tests/simulation/translator/test_output_translation.py
Labels: Hotfix-pending

#715 [SCFD-4264] fix(): Add validation to prevent steady simulation with aeroacoustics (#713)
  flow360/component/simulation/simulation_params.py
  flow360/component/simulation/validation/validation_output.py
  tests/simulation/params/test_validators_output.py
  tests/simulation/translator/test_output_translation.py
Labels: Hotfix-pending

#685 Revert "[NEEDS REVERT BACK] Temporary reverted temperature related fixes because they are not tested yet and I need to deploy a new version. (#684)"
  examples/migration_guide/extra_operating_condition.py
  flow360/component/simulation/conversion.py
  flow360/component/simulation/models/material.py
  flow360/component/simulation/models/surface_models.py
  flow360/component/simulation/operating_condition/operating_condition.py
  flow360/component/simulation/services.py
  flow360/component/simulation/simulation_params.py
  flow360/component/simulation/unit_system.py
  flow360/component/v1/unit_system.py
  flow360/log.py
  tests/simulation/framework/test_unit_system_v2.py
  tests/simulation/params/test_simulation_params.py
  tests/simulation/params/test_unit_conversions.py
  tests/simulation/service/data/simulation_param.json
  tests/simulation/service/ref/unit_system_converted_CGS.json
  tests/simulation/service/ref/unit_system_converted_SI.json
  tests/simulation/service/ref/unit_system_converted_imperial.json
  tests/simulation/service/test_services_v2.py
  tests/v1/test_unit_system_v1.py
Labels: BLOCKED, Testing-pending

#739 removed sys.stdout to fix jupyter notebooks
  flow360/log.py
Labels: Hotfix-pending

#775 [HOTFIX] add updater to 24.11.10 to 25.2
  flow360/component/simulation/framework/updater.py
  tests/data/simulation/simulation_24_11_9.json
  tests/simulation/test_updater.py
Labels: Hotfix-pending
